### ISSUE TITLE
Support for IP Security Restrictions Mode

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/terraform-azure-container-apps#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Support the "IP Security Restrictions Mode" feature of ingress where you can allow/deny given IP-ranges on the ingress.

### New or Affected Resource(s)/Data Source(s)

N/A

### Potential Terraform Configuration

```hcl
Should only require new inputs to the terraform module, it will be backwards compatible because it is new parameters and won't affect existing mode.
```

### References

https://learn.microsoft.com/en-us/azure/container-apps/ip-restrictions?pivots=azure-portal

update: seems to be needed in the the terraform resource as well: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_app, tracked in https://github.com/hashicorp/terraform-provider-azurerm/issues/21774

**Comment by lonegunmanb** [comment]
Hi @davidkarlsen thanks for submitting this feature to this module, I'd like to track the (feature request in the provider)[https://github.com/hashicorp/terraform-provider-azurerm/issues/21774], once it has been solved then we can see what can do in this module.

**Comment by davidkarlsen** [comment]
I've added a PR to the provider.

**Comment by davidkarlsen** [comment]
@lonegunmanb It will come in the next provider release: https://github.com/hashicorp/terraform-provider-azurerm/pull/23870

**Comment by davidkarlsen** [comment]
It is GA now.
