### ISSUE TITLE
Support for existing container apps environment

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/terraform-azure-container-apps#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

It would be good to create the container apps conditionally, and only if user does not provide a reference to an existing container apps environment.

### New or Affected Resource(s)/Data Source(s)

azurerm_container_app_environment

### Potential Terraform Configuration

```hcl
new nullable input var `container_app_environment`, if non-null, use this, and use a

count = var.container_app_environment == 0 ? 1

on the one in the module.
```

**Comment by lonegunmanb** [comment]
I like this idea, especially now we're still at `v0`, which means we can introduce any breaking changes as we like.
