### ISSUE TITLE
Support for key vault references

### ISSUE THREAD

**Issue by epa095** [Azure/terraform-azure-container-apps#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Its possible to have secrets based on a key-vault reference, https://learn.microsoft.com/en-us/azure/container-apps/manage-secrets?tabs=arm-template#reference-secret-from-key-vault

**But can it be done with this module?** 

I tried the following, but then it complained that I need "value". If I put the keyvault URI in the value, then the URL itself becomes the secret.

```terraform

  container_app_secrets = {
    nginx= [
      {
        name        = "secret"
        keyVaultUrl = "https://somethingvault.azure.net/secrets/thesecret"
        identity    = "system"
      }
    ]
  }
```

### New or Affected Resource(s)/Data Source(s)

N/A

### References

 https://learn.microsoft.com/en-us/azure/container-apps/manage-secrets?tabs=arm-template#reference-secret-from-key-vault

**Comment by lonegunmanb** [comment]
Thanks @epa095 for opening this pr! I've checked the [provider's schema](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/containerapps/helpers/container_apps.go#L2552-L2576), we need add KeyVaultUrl support there first.

I'll open a pr to the provider's repo.

**Comment by matthew-patrick** [comment]
It looks like it was implemented into tf provider. Is there an anticipated timelike for when this can be implemented into the module as well as a documentation update?
