### ISSUE TITLE
Add support for httpMaxRequestSize in dapr configuration

### ISSUE THREAD

**Issue by rodyvansambeek** [Azure/terraform-azure-container-apps#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I am using the settings at the Dapr configuration like: 
- httpMaxRequestSize = int
- httpReadBufferSize = int
- logLevel = "string"

See: https://learn.microsoft.com/en-us/azure/templates/microsoft.app/containerapps?pivots=deployment-language-terraform

You can also set these options using the Azure Portal, but there seems to be no option using the terraform definitions. 

I tried: 

```yaml
resource "azurerm_container_app" "example" {
  name                         = "example"
  container_app_environment_id = ...
  resource_group_name          = ...
  revision_mode                = "Single"
  dapr {
    app_id = "ca-cn-import"
    http_max_request_size = 16000000
  }

```

but that didn't work unfortunately

### New or Affected Resource(s)/Data Source(s)

azurerm_container_app

### Potential Terraform Configuration

```hcl
resource "azurerm_container_app" "example" {
  name                         = "example"
  container_app_environment_id = ...
  resource_group_name          = ...
  revision_mode                = "Single"
  dapr {
    app_id = "ca-cn-import"
    http_max_request_size = 16000000   <------
  }
```

**Comment by lonegunmanb** [comment]
Hello @rodyvansambeek thanks for opening this issue to us! This request looks like a request to [`azurerm` provider](https://github.com/hashicorp/terraform-provider-azurerm), so would you please open an issue there? This module couldn't support this feature unless the provider already supported it. Thanks for your understanding!

**Comment by rodyvansambeek** [comment]
@lonegunmanb Ah, I see, you are right. I will open up a new issue there to see if we can manage to get it added in the azurerm provider. Thanks!
