### ISSUE TITLE
Support for instrumentation key for container app environment 

### ISSUE THREAD

**Issue by RMASolutions** [Azure/terraform-azure-container-apps#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

add support for instrumentation key for app insight for dapr
in CLI we use the parameter --dapr-instrumentation-key
only possible during the az container app env creation 

### New or Affected Resource(s)/Data Source(s)

azurerm-container-apps

**Comment by lonegunmanb** [comment]
@RMASolutions thanks for opening this request to us, I've checked this [document](https://learn.microsoft.com/en-us/cli/azure/containerapp/env?view=azure-cli-latest#az-containerapp-env-create) and found that `--dapr-instrumentation-key` flag has been deprecated, so I cannot support this feature and I'm closing this issue. Please feel free to reopen it and ping me here if you have different thought.

If you have other features that like to be added in this module, would you please give us the arguments you'd like to use in the corresponding AzureRM resource? Thanks!
